spring:
 profiles:
  active: dev
 http:
  encoding:
   force: true
 datasource:    
   driver-class-name: com.mysql.jdbc.Driver    
   url: jdbc:mysql://localhost:3306/springboot    
   username: root    
   password: root

mybatis:
 mapper-locations: classpath:mybatis/mapper/*.xml
 config-location: classpath:mybatis/mybatis-config.xml